import {test,expect} from '@playwright/test';
test('search, editorial Home and reading preferences work',async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('./');
 await expect(page.locator('.lead-story')).toBeVisible();
 await expect(page.locator('.focus-rail')).toBeVisible();
 await expect(page.locator('.latest-zone')).toBeVisible();
 await expect(page.locator('[data-slide]')).toHaveCount(0);
 await page.goto('./busca/?q=Brasil');
 await expect(page.locator('#search-results article').first()).toBeVisible();
 await page.getByRole('searchbox').fill('zzzzsemresultado999');
 await page.getByRole('button',{name:'Buscar ↗'}).click();
 await expect(page.locator('#search-status')).toHaveText('0 notícias encontradas.');
 await page.getByRole('searchbox').fill('Brasil');await page.getByRole('button',{name:'Buscar ↗'}).click();
 await page.locator('#search-results h2 a').first().click();
 await page.getByText('Ajustar leitura',{exact:true}).click();
 await page.getByRole('button',{name:'Aumentar texto'}).click();
 await expect(page.locator('html')).toHaveAttribute('style',/--reading-scale: 1.1/);
 await page.getByRole('button',{name:'Alto contraste'}).click();
 await expect(page.getByRole('button',{name:'Alto contraste'})).toHaveAttribute('aria-pressed','true');
 await page.reload();await expect(page.locator('html')).toHaveClass(/reading-contrast/);
 await expect(page.locator('[data-speak]')).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect(errors).toEqual([]);
});
test('status never reports a failed request as live success',async({page})=>{
 await page.route('https://api.github.com/**',route=>route.fulfill({status:503,body:'unavailable'}));
 await page.goto('./status/');
 await expect(page.locator('[data-operation-live]')).toContainText('Estado ao vivo indisponível');
});
