import {read,write,toggle,toggleSaved} from './store.js';
import {applyHome} from './global.js';
import {bindPortability} from './portability.js';
const parseData=()=>{try{return JSON.parse(document.getElementById('apurante-plus-data')?.textContent||'{}');}catch{return {};}};
const makeStory=article=>{const item=document.createElement('article');item.className='ap-saved-item ap-feed-item';const body=document.createElement('div');const meta=document.createElement('span');meta.className='eyebrow';meta.textContent=article.category;const title=document.createElement('h3');const link=document.createElement('a');link.href=article.url;link.textContent=article.title;title.append(link);const desc=document.createElement('p');desc.textContent=article.description;body.append(meta,title,desc);item.append(body);return item;};
export function initPanel(){
  const root=document.querySelector('[data-ap-panel]');if(!root)return;const data=parseData();const articles=Array.isArray(data.articles)?data.articles:[];const bySlug=new Map(articles.map(a=>[a.slug,a]));const categories=Array.isArray(data.categories)?data.categories:[];
  const render=()=>{const state=read();root.querySelectorAll('[data-ap-preferred]').forEach(input=>input.checked=state.categories.includes(input.value));root.querySelectorAll('[data-ap-topic]').forEach(button=>{const active=state.topics.includes(button.dataset.apTopic);button.setAttribute('aria-pressed',String(active));button.classList.toggle('is-active',active);});const enabled=root.querySelector('[data-ap-home-enabled]');if(enabled)enabled.checked=state.home.enabled;renderHome(state);renderSaved(state);renderFeed(state);};
  const renderSaved=state=>{const host=root.querySelector('[data-ap-saved-list]');if(!host)return;host.replaceChildren();if(!state.saved.length){host.innerHTML='<p class="ap-empty">Nenhuma matéria salva neste navegador.</p>';return;}state.saved.forEach(slug=>{const article=bySlug.get(slug);const item=article?makeStory(article):document.createElement('article');if(!article){item.className='ap-saved-item';item.textContent=slug;}const remove=document.createElement('button');remove.type='button';remove.className='ap-inline-button';remove.textContent='Remover';remove.addEventListener('click',()=>{toggleSaved(slug,false);render();});item.append(remove);host.append(item);});};
  const renderFeed=state=>{const host=root.querySelector('[data-ap-plus-feed]');if(!host)return;host.replaceChildren();const matches=articles.filter(a=>state.categories.includes(a.category)||a.tags?.some(tag=>state.topics.includes(tag))).slice(0,18);const count=root.querySelector('[data-ap-plus-count]');if(count)count.textContent=matches.length?`${matches.length} notícias relacionadas`:'';if(!matches.length){host.innerHTML='<p class="ap-empty">Escolha uma editoria ou siga um assunto para montar seu feed local.</p>';return;}matches.forEach(a=>host.append(makeStory(a)));};
  const orderFor=state=>[...state.home.order.filter(c=>categories.includes(c)),...categories.filter(c=>!state.home.order.includes(c))];
  const renderHome=state=>{const host=root.querySelector('[data-ap-home-categories]');if(!host)return;const order=orderFor(state);const rows=new Map([...host.children].map(row=>[row.dataset.category,row]));order.forEach((category,index)=>{const row=rows.get(category);if(!row)return;row.querySelector('[data-ap-home-visible]').checked=!state.home.hidden.includes(category);const up=row.querySelector('[data-ap-up]');const down=row.querySelector('[data-ap-down]');up.disabled=index===0;down.disabled=index===order.length-1;host.append(row);});};
  root.addEventListener('change',event=>{const input=event.target;if(!(input instanceof HTMLInputElement))return;const state=read();if(input.matches('[data-ap-preferred]'))state.categories=toggle(state.categories,input.value,input.checked);if(input.matches('[data-ap-home-enabled]'))state.home.enabled=input.checked;if(input.matches('[data-ap-home-visible]'))state.home.hidden=toggle(state.home.hidden,input.value,!input.checked);write(state);render();applyHome();});
  root.addEventListener('click',event=>{const target=event.target instanceof Element?event.target:null;if(!target)return;const topic=target.closest('[data-ap-topic]');if(topic){const state=read();state.topics=toggle(state.topics,topic.dataset.apTopic);write(state);render();return;}const move=target.closest('[data-ap-up],[data-ap-down]');if(move){const row=move.closest('[data-category]');const state=read();const order=orderFor(state);const from=order.indexOf(row.dataset.category);const to=from+(move.matches('[data-ap-up]')?-1:1);if(to>=0&&to<order.length){[order[from],order[to]]=[order[to],order[from]];state.home.order=order;write(state);render();applyHome();}}});
  bindPortability(root,render);render();
}
